baseURL = "https://borntosquad.com/"
languageCode = "de-DE"
title = "Born To Squad"
theme = "hugograyscale"

[params]
    # Provide some metadata for search and indexing services
    description = "Website of the Join Squad Game Clan Born To Squad"
    author = "Born To Squad"

[Author]
    name = "Born To Squad"
    bio = "Willkommen auf der Born To Squad Webseite"